name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file myapp/pom.xml

    - name: Extract current version
      id: extract-version
      run: |
        VERSION=$(mvn -f myapp/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Increment patch version
      id: increment-version
      run: |
        VERSION=${{ env.version }}
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        PATCH=$((PATCH+1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "New version: $NEW_VERSION"
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

    - name: Update pom.xml with new version
      run: |
        mvn -f myapp/pom.xml versions:set -DnewVersion=${{ env.new_version }}
        mvn -f myapp/pom.xml versions:commit

    - name: Commit and push updated version
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add myapp/pom.xml
        git diff --cached --exit-code || (git commit -m "Bump version to ${{ env.new_version }}" && git push)

    - name: Build Docker Image
      run: |
        echo "Building Docker image with version ${{ env.new_version }}"
        docker build -t myapp:${{ env.new_version }} .
        docker tag myapp:${{ env.new_version }} mydockerhub/myapp:${{ env.new_version }}
