name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn clean install -f myapp/pom.xml
        ls -l myapp/target

    - name: Extract current version
      id: extract-version
      run: |
        VERSION=$(mvn -f myapp/pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        echo "Building Docker image with version ${{ env.version }}"
        docker build -t matan2024/myapp:${{ env.version }} .
        docker tag matan2024/myapp:${{ env.version }} matan2024/myapp:latest

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image to Docker Hub
      run: |
        docker push matan2024/myapp:${{ env.version }}
        docker push matan2024/myapp:latest

    # - name: Run Docker Container Locally
    #   run: |
    #     docker run -d --name myapp-container -p 8082:8080 matan2024/myapp:${{ env.version }}
    #     sleep 10
    #     curl -f http://localhost:8082 || (echo "App did not start successfully" && exit 1)
